import { OptionItem } from './types';

export const TYPE_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: 'MASTER', label: 'Master' },
  { value: 'REVIEW', label: 'Review' },
  { value: 'ONLINE', label: 'Online' },
  { value: 'OFFLINE', label: 'Offline' },
  { value: 'LOCKCUT', label: 'Lock Cut' },
  { value: 'MIXCUT', label: 'Mix Cut' },
  { value: 'SCREENER', label: 'Screener' },
  { value: 'TURNOVER', label: 'Turn Over' },
  { value: 'RENDER', label: 'Render' },
  { value: 'OCF', label: 'Original Camera Footage' },
  { value: 'RAW', label: 'Raw Media' },
  { value: 'VFX', label: 'Visual Effect' },
  { value: 'COMP', label: 'Composed VFX' },
  { value: 'PROD', label: 'Product' },
  { value: 'SHORT', label: 'Short' },
  { value: 'VERTICAL', label: 'Vertical' },
  { value: 'IG', label: 'Instagram' },
  { value: 'TIKTOK', label: 'TikTok' },
  { value: 'YT', label: 'YouTube' },
  { value: 'STORY', label: 'Story' },
  { value: 'REEL', label: 'Reel' },
];

export const LANGUAGE_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: 'es', label: 'Español (Genérico)' },
  { value: 'es-419', label: 'Español Latinoamericano' },
  { value: 'es-ES', label: 'Español (España / Castellano)' },
  { value: 'es-MX', label: 'Español (México)' },
  { value: 'es-US', label: 'Español (Estados Unidos)' },
  { value: 'es-AR', label: 'Español (Argentina)' },
  { value: 'es-CL', label: 'Español (Chile)' },
  { value: 'es-CO', label: 'Español (Colombia)' },
  { value: 'en', label: 'Inglés (Genérico)' },
  { value: 'en-US', label: 'Inglés (Estados Unidos)' },
  { value: 'en-GB', label: 'Inglés (Reino Unido)' },
  { value: 'en-CA', label: 'Inglés (Canadá)' },
  { value: 'en-AU', label: 'Inglés (Australia)' },
  { value: 'en-NZ', label: 'Inglés (Nueva Zelanda)' },
  { value: 'fr-FR', label: 'Francés (Francia)' },
  { value: 'pt-BR', label: 'Portugués (Brasil)' },
  { value: 'pt-PT', label: 'Portugués (Portugal)' },
  { value: 'de-DE', label: 'Alemán (Alemania)' },
  { value: 'it-IT', label: 'Italiano (Italia)' },
  { value: 'ja-JP', label: 'Japonés' },
];

export const SUBTITLE_TYPE_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: 'CLN', label: 'Textless / Clean' },
  { value: 'SUB', label: 'Subtitled' },
  { value: 'BURN', label: 'Burned-In' },
  { value: 'FRC', label: 'Forced Subs' },
  { value: 'CC', label: 'Closed Captions' },
  { value: 'SDH', label: 'SDH' },
  { value: 'CAP', label: 'Captions' },
];

export const RESOLUTION_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: 'SD-NTSC', label: 'SD NTSC (720x486)' },
  { value: 'SD-PAL', label: 'SD PAL (720x576)' },
  { value: 'HD', label: 'HD (1280x720)' },
  { value: 'FHD', label: 'Full HD (1920x1080)' },
  { value: 'VHD', label: 'Vertical HD (1080x1920)' },
  { value: 'QHD', label: 'Quad HD-Wide (2560x1440)' },
  { value: 'UHD', label: 'Ultra HD (3840x2160)' },
  { value: '2K-DCI', label: '2k DCI (2048x1080)' },
  { value: '2K-FLAT', label: '2k DCP Flat (1998x1080)' },
  { value: '2K-SCOPE', label: '2k DCP scope (2048x858)' },
  { value: '4K-DCI', label: '4K DCI (4096x2160)' },
  { value: '4K-FLAT', label: '4K DCP Flat (3996x2160)' },
  { value: '4K-SCOPE', label: '4K DCP Scope (4096x1716)' },
  { value: '8K-DCI', label: '8K DCI (8192x4320)' },
];

export const COLOR_SPACE_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: 'SDR', label: 'SDR' },
  { value: 'HDR', label: 'HDR' },
  { value: 'REC709', label: 'Rec709' },
  { value: 'REC2020', label: 'Rec2020' },
  { value: 'P3D65', label: 'P3D65' },
  { value: 'P3-DCI', label: 'P3-DCI' },
  { value: 'ARRILOG', label: 'Arri LogC' },
  { value: 'BLCKMFILM', label: 'Blackmagic Design Film' },
  { value: 'REDLOG', label: 'RED Log' },
  { value: 'SLOG', label: 'Sony SLog' },
  { value: 'ACES-CG', label: 'ACES CG' },
  { value: 'ACES-AP0', label: 'ACES AP0' },
  { value: 'ACES-AP1', label: 'ACES AP1' },
  { value: 'DCDM', label: 'DCDM' },
];

export const LUMINANCE_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: '4000', label: '4000 Nits' },
  { value: '1000', label: '1000 Nits' },
  { value: '600', label: '600 Nits' },
  { value: '300', label: '300 Nits' },
  { value: '100', label: '100 Nits' },
  { value: '48', label: '48 Nits' },
];

export const CONTAINER_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: 'MOV', label: 'MOV' },
  { value: 'AVI', label: 'AVI' },
  { value: 'MP4', label: 'MP4' },
  { value: 'IMF', label: 'IMF' },
  { value: 'MXF', label: 'MXF' },
  { value: 'TIFF', label: 'TIFF' },
  { value: 'DPX', label: 'DPX' },
  { value: 'EXR', label: 'EXR' },
];

export const COMPRESOR_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: 'PR4444XQ', label: 'ProRes 4444XQ' },
  { value: 'PR4444', label: 'ProRes 444' },
  { value: 'PR422HQ', label: 'ProRes 422HQ' },
  { value: 'PRPXY', label: 'ProRes Proxy' },
  { value: 'PRLT', label: 'ProRes LT' },
  { value: 'DNx44412bit', label: 'DNxHR 444 12-bit' },
  { value: 'DNx44410bit', label: 'DNxHR 444 10-bit' },
  { value: 'DNx444HQX12bit', label: 'DNxHR 444 HQX-12bit' },
  { value: 'DNx444HQX10bit', label: 'DNxHR 444 HQX-10bit' },
  { value: 'DNx-HQ', label: 'DNxHR HQ' },
  { value: 'DNx-SQ', label: 'DNxHR SQ' },
  { value: 'DNx-LB', label: 'DNxHR LB' },
  { value: 'H264', label: 'H264' },
  { value: 'H265', label: 'H265' },
  { value: 'MPEG', label: 'Mpeg' },
  { value: '10bit', label: '10bit' },
  { value: '12bit', label: '12bit' },
  { value: '16bit', label: '16bit' },
  { value: 'UNCOMPRESSED', label: 'Uncompressed' },
];

export const FRAMERATE_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: '2398', label: '23.98' },
  { value: '24', label: '24' },
  { value: '25', label: '25' },
  { value: '2997', label: '29.97' },
  { value: '30', label: '30' },
  { value: '4795', label: '47.952' },
  { value: '48', label: '48' },
  { value: '50', label: '50' },
  { value: '5994', label: '59.94' },
  { value: '60', label: '60' },
  { value: '72', label: '72' },
  { value: '96', label: '96' },
  { value: '1198', label: '119.88' },
  { value: '120', label: '120' },
];

export const ASPECT_RATIO_OPTIONS: OptionItem[] = [
  { value: 'NONE', label: 'NONE' },
  { value: '133', label: '1:33' },
  { value: '166', label: '1:66' },
  { value: '177', label: '1:77' },
  { value: '185', label: '1:85' },
  { value: '20', label: '2:0' },
  { value: '235', label: '2:35' },
  { value: '239', label: '2:39' },
  { value: '240', label: '2:40' },
  { value: '43', label: '4:3' },
  { value: '11', label: '1:1' },
  { value: '169', label: '16:9' },
  { value: '916', label: '9:16' },
];

export const SOUND_OPTIONS: OptionItem[] = [
  { value: 'MOS', label: 'No Sound' },
  { value: '20', label: 'Stereo 2.0' },
  { value: '51', label: 'Surround 5.1' },
  { value: '71', label: 'Surround 7.1' },
  { value: 'ATMOS', label: 'Atmos' },
  { value: 'ME20', label: 'M&E 2.0' },
  { value: 'ME51', label: 'M&E 5.1' },
  { value: 'STEM10', label: 'STEMS 1.0' },
  { value: 'STEM20', label: 'STEMS 2.0' },
  { value: 'STEM51', label: 'STEMS 5.1' },
  { value: 'DX10', label: 'Dialog 1.0' },
  { value: 'SFX10', label: 'Sound FX 1.0' },
  { value: 'MX10', label: 'Music 1.0' },
  { value: 'DX20', label: 'Dialog 2.0' },
  { value: 'SFX20', label: 'Sound FX 2.0' },
  { value: 'MX20', label: 'Music 2.0' },
];